# Generated by Django 2.2.15 on 2020-08-15 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HelloWorld',
            new_name='World',
        ),
    ]
